site_name: RedisGears
site_url: http://redisgears.io
repo_url: https://github.com/RedisGears/RedisGears
repo_name: RedisGears/RedisGears

google_analytics:
  - 'UA-92003007-1'
  - 'auto'

extra_javascript:
  - gtm.js

use_directory_urls: false

theme:
  name: 'material'
  language: 'en'
  logo: 'images/RedisGears.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

nav:
  - 'Home': 'index.md'
  - 'Quickstart': 'quickstart.md'
  - 'Introduction': 'intro.md'
  - 'Reference':
    - 'Runtime': 'runtime.md'
    - 'Functions': 'functions.md'
    - 'Readers': 'readers.md'
    - 'Operations': 'operations.md'
    - 'Commands': 'commands.md'
    - 'Configuration': 'configuration.md'
  - 'Examples': 'examples.md'
  - 'Clients': 'clients.md'
  - 'Design':
    - 'Isolation Technics': 'isolation_technics.md'
  - 'Glossary': 'glossary.md'
  - 'Contributing': 'contrib.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: True

plugins:
  - search
  - include:
      src_path: docs/snippets
  - versions-menu:
      exclude-regexes:
        - '0\.[1-4]'
      include-regex: '([0-9]+)\.([0-9]+)'
