site_name: RedisGears - Programmable engine for data processing in Redis
site_url: http://redisgears.io
repo_url: https://github.com/RedisGears/RedisGears
repo_name: RedisGears/RedisGears

google_analytics:
  - 'UA-92003007-1'
  - 'auto'

extra_javascript:
  - gtm.js

use_directory_urls: false

theme:
  name: 'material'
  language: 'en'
  logo: 'images/RedisGears.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

nav:
  - 'Home': 'index.md'
  - 'Quickstart': 'quickstart.md'
  - 'Introduction': 'intro.md'
  - 'Reference':
    - 'Runtime': 'runtime.md'
    - 'Functions': 'functions.md'
    - 'Readers': 'readers.md'
    - 'Operations': 'operations.md'
    - 'Commands': 'commands.md'
    - 'RedisAI': 'redisai.md'
    - 'Configuration': 'configuration.md'
  - 'Examples': 'examples.md'
  - 'Clients': 'clients.md'
  - 'Advanced Topics':
    - 'Isolation Techniques': 'isolation.md'
    - 'Async Await Advanced Topics': 'async_await_advance_topics.md'
    - 'Commands Hook': 'commands_hook.md'
    - 'Key Miss Event': 'miss_event.md'
  - 'Glossary': 'glossary.md'
  - 'Contributing': 'contrib.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: True

plugins:
  - search
  - include:
      src_path: docs/snippets
  - modules-template:
      try-for-free: false
      modules:
        - name: 'Search'
          link: '/redisearch'

        - name: 'Time Series'
          link: '/redistimeseries'

        - name: 'Bloom'
          link: '/redisbloom'

        - name: 'Graph'
          link: '/redisgraph'

        - name: 'JSON'
          link: '/redisjson'

        - name: 'AI'
          link: '/redisai'
  - versions-menu:
      exclude-regexes:
        - '0\.[1-4]'
      include-regex: '([0-9]+)\.([0-9]+)'
