name: Centos 7

on:
  workflow_call:
    inputs:
      v8_version:
        default: 'default'
        required: false
        type: string
      v8_update_headers:
        default: 'no'
        required: false
        type: string
      redis_version:
        default: 7.2-rc1
        required: false
        type: string
      upload_artifacts:
        default: false
        required: false
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_KEY_ID:
        required: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:centos7

    steps:
    - name: Update yum
      run: yum update -qqy
    - name: Install requirements 
      run: |
        yum install -yqq openssl wget python3 xz-utils lsb-release sudo dialog apt-utils redhat-lsb subversion chrpath openssl-devel python3-devel
        yum groupinstall -yqq 'Development Tools'
        yum install -yqq centos-release-scl
        yum install -yqq devtoolset-9 llvm-toolset-7
        pip3 install --upgrade pip
    - name: Install latest git
      run: |
        yum -yqq install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        yum install -yqq git
    - name: Install python38
      run: |
        yum -yqq install centos-release-scl-rh
        yum -yqq install rh-python38-python
        yum -yqq install rh-python38-python-pip
    - uses: actions/checkout@v3
    - name: Add RedisGears directory to git safe directory
      run: git config --global --add safe.directory /__w/RedisGears/RedisGears
    - name: install rltest
      run: /opt/rh/rh-python38/root/usr/bin/python -m pip install RLTest
    - name: Install redis
      run: |
        set -x
        . scl_source enable  devtoolset-9 || true
        . scl_source enable llvm-toolset-7 || true
        git clone https://github.com/redis/redis
        cd redis
        git checkout ${{ inputs.redis_version }}
        make install
    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install_rust.sh
        sh install_rust.sh -y
    - name: format
      run: $HOME/.cargo/bin/cargo fmt -- --check
    - name: Build
      run: |
        . scl_source enable  devtoolset-9 || true
        . scl_source enable llvm-toolset-7 || true
        V8_VERSION=${{ inputs.v8_version }} V8_UPDATE_HEADERS=${{ inputs.v8_update_headers }} $HOME/.cargo/bin/cargo build -vv
        V8_VERSION=${{ inputs.v8_version }} V8_UPDATE_HEADERS=${{ inputs.v8_update_headers }} $HOME/.cargo/bin/cargo build --release -vv
    - name: Tests
      run: |
        PATH=/opt/rh/rh-python38/root/usr/local/bin:$PATH
        cd pytests;./run_tests.sh
    - name: install ramp packer
      run: /opt/rh/rh-python38/root/usr/bin/python -m pip install git+https://github.com/RedisLabsModules/RAMP.git@master
    - name: Pack
      run: |
        PATH=/opt/rh/rh-python38/root/usr/local/bin:$PATH
        target/release/packer
      env:
          LC_ALL: en_US.utf-8
          LANG: en_US.utf-8
    - name: Setup s3cmd action
      if: ${{ inputs.upload_artifacts }}
      uses: s3-actions/s3cmd@v1.2.0
      with:
        provider: aws
        region: us-east-2
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload artifacts
      if: ${{ inputs.upload_artifacts }}
      run: |
        s3cmd put -P target/release/redisgears2.Linux-rhel7-x86_64.master.zip s3://redismodules/redisgears/snapshots/
