---

name: Build dockers

on:

  push:
#    branches:
#      - master
#    tags:
#      - 'v[0-9].[0-9].[0-9]-rc[0-9]+'
#      - 'v[0-9].[0-9].[0-9]-m[0-9]+'

  workflow_dispatch:

jobs:

  docker:
    name: Build dockers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
          platforms: linux/amd64,linux/arm64/v8

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push in master
        uses: docker/build-push-action@v4
        if: ${{ github.event.release.tag_name == '' }}
        with:
          push: false
          tags: ${{ vars.DOCKERHUB_REPO }}:edge
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

      - name: build and push on release
        uses: docker/build-push-action@v4
        if: ${{ github.event.release.tag_name != '' }}
        with:
          push: false
          tags: ${{ vars.DOCKERHUB_REPO }}:${{ github.event.release.tag_name }}
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
