name: Macos Latest

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install rltest
      run: python3 -m pip install RLTest\
    - name: install automake
      run: brew install automake
    - name: install openssl
      run: brew install openssl@1.1
    - name: install redis
      run: git clone https://github.com/redis/redis; cd redis; git checkout 7.0.3; make install
    - name: format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
      env:
        PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig/
        OPENSSL_PREFIX: /usr/local/opt/openssl@1.1
    - name: Tests
      run: cd pytests; python3 -m RLTest
