name: Macos

on:
  workflow_call:
    inputs:
      v8_version:
        default: 'default'
        required: false
        type: string
      v8_update_headers:
        default: 'no'
        required: false
        type: string
      redis_version:
        default: 7.2-rc1
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest
    env:
      V8_VERSION: ${{ inputs.v8_version }}
      V8_UPDATE_HEADERS: ${{ inputs.v8_update_headers }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install rltest
      run: |
        python3 -m pip install RLTest
        python3 -m pip install -U redis==5.0.0b3
    - name: install automake
      run: brew install automake
    - name: install openssl
      run: brew install openssl@1.1
    - name: install redis
      run: git clone https://github.com/redis/redis; cd redis; git checkout ${{ inputs.redis_version }}; make install
    - name: format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
      env:
        PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig
        OPENSSL_PREFIX: /usr/local/opt/openssl@1.1
    - name: Unit tests
      run: $HOME/.cargo/bin/cargo test --verbose
    - name: Integration tests
      run: cd pytests; python3 -m RLTest
