name: MSRV

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  rust_msrv: 1.63.0

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:bionic

    steps:
    - name: Update apt
      run: apt update
    - name: Install pre-requisites
      run: |
        apt -yqq install software-properties-common
        add-apt-repository ppa:deadsnakes/ppa
        add-apt-repository ppa:ubuntu-toolchain-r/test
        apt update
        apt -yqq install git gcc-9 g++-9 curl wget python3.10 python3.10-dev dialog subversion chrpath libssl-dev python3-dev clang autoconf automake libtool libssl-dev pkg-config
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 10
        curl -sS https://bootstrap.pypa.io/get-pip.py | python3
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
    - uses: actions/checkout@v3
    - name: Install toolchain (${{ env.rust_msrv }})
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain="${{ env.rust_msrv }}"
    - name: update pip3
      run: python3 -m pip install -U pip
    - name: install rltest
      run: |
        python3 -m pip install RLTest
        python3 -m pip install -U redis==5.0.0b3
    - name: install redis
      run: git clone https://github.com/redis/redis; cd redis; git checkout 7.2-rc1; make install
    - name: Build debug
      run: $HOME/.cargo/bin/cargo build --verbose
    - name: Build release
      run: $HOME/.cargo/bin/cargo build --release --verbose
    - name: Unit tests
      run: $HOME/.cargo/bin/cargo test --verbose
    - name: Integration tests
      run: cd pytests; ./run_tests.sh
