name: Ubuntu Focal

on:
  workflow_call:
    inputs:
      v8_version:
        default: 'default'
        required: false
        type: string
      v8_update_headers:
        default: 'no'
        required: false
        type: string
      redis_version:
        default: 7.2-rc1
        required: false
        type: string
      upload_artifacts:
        default: false
        required: false
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04
    env:
      V8_VERSION: ${{ inputs.v8_version }}
      V8_UPDATE_HEADERS: ${{ inputs.v8_update_headers }}

    steps:
    - uses: actions/checkout@v3
    - name: install rltest
      run: |
        pip install RLTest
        python -m pip install -U redis==5.0.0b3
    - name: install redis
      run: git clone https://github.com/redis/redis; cd redis; git checkout ${{ inputs.redis_version }}; make install
    - name: format
      run: cargo fmt -- --check
    - name: Build debug
      run:  cargo build --verbose
    - name: Build release
      run:  cargo build --release --verbose
    - name: Unit tests
      run: $HOME/.cargo/bin/cargo test --verbose
    - name: Integration tests
      run: cd pytests;./run_tests.sh
    - name: install ramp packer
      run: pip install git+https://github.com/RedisLabsModules/RAMP.git@master
    - name: Pack
      run: target/release/packer
    - name: Setup s3cmd action
      if: ${{ inputs.upload_artifacts }}
      uses: s3-actions/s3cmd@v1.2.0
      with:
        provider: aws
        oegion: us-east-2
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload artifacts
      if: ${{ inputs.upload_artifacts }}
      run: |
        s3cmd put -P target/release/redisgears2.Linux-ubuntu22.04-x86_64.master.zip s3://redismodules/redisgears/snapshots/
