name: Ubuntu Focal

on:
  workflow_call:
    inputs:
      v8_version:
        default: 'default'
        required: false
        type: string
      v8_update_headers:
        default: 'no'
        required: false
        type: string
      redis_version:
        required: true
        type: boolean
      upload_artifacts:
        default: false
        required: false
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_KEY_ID:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: install rltest
      run: pip install RLTest
    - name: install redis
      run: git clone https://github.com/redis/redis; cd redis; git checkout ${{ inputs.redis_version }}; make install
    - name: format
      run: cargo fmt -- --check
    - name: Build debug
      run: V8_VERSION=${{ inputs.v8_version }} V8_UPDATE_HEADERS=${{ inputs.v8_update_headers }} cargo build --verbose
    - name: Build release
      run: V8_VERSION=${{ inputs.v8_version }} V8_UPDATE_HEADERS=${{ inputs.v8_update_headers }} cargo build --release --verbose
    - name: Tests
      run: cd pytests;./run_tests.sh
    - name: install ramp packer
      run: pip install git+https://github.com/RedisLabsModules/RAMP.git@master
    - name: Pack
      run: target/release/packer
    - name: Setup s3cmd action
      if: ${{ inputs.v8_update_headers }}
      uses: s3-actions/s3cmd@v1.2.0
      with:
        provider: aws
        region: us-east-2
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload artifacts
      if: ${{ inputs.v8_update_headers }}
      run: |
        s3cmd put -P target/release/redisgears2-release.linux-ubuntu.20.04-x86_64.master.zip s3://redismodules/redisgears/snapshots/
